language: node_js
node_js:
    - 'stable'
cache:
    directories:
        - node_modules
script:
    - yarn test
    - yarn tslint
# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $githubToken
#   local_dir: build
#   on:
#     branch: master
